### PR TITLE
Lodash was missing from the package.json

### PR DESCRIPTION
**Pull request by ch222kv**

### CODE REVIEW

**Comment by ch222kv** [comment]
And of course you push 2 minutes before :(

**Comment by krawaller** [comment]
Hups, good catch, thank you!

Sorry about the push, but I know that you have [lots of experience](https://github.com/krawaller/riaguild2015/pull/105) in solving merge conflicts... :D

**Comment by ch222kv** [comment]
Haha, it's such a small change that it barely justifies a PR, but I couldn't build the project without lodash, so it was necessary. :)

**Comment by krawaller** [comment]
no it was a good catch! that's what happens when you copy a previous project including the `node_modules` folder, really dumb move :P

**Pull request merged**
